# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6370d066bb36ec90b82c50f79a3733cd496e7acf9ddc4d07119e86033a7a52e4f05c1623c29a8336a33de81b213d46463d11d3004e1246b7534643c22f1d13

test:
  secret_key_base: 842de166588679116e7e86d31509a5fbdbe38a389357971b0af34868cae60997ca8ed384f2afcf7bf8669a404903aee37949f28596bee577aeef38b980951bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
